#include <QDesktopWidget>
#include <QOpenGLWidget>
#include <QPainter>
#include <QWheelEvent>
#include <QColor>
#include <QDebug>
#include <QThread>
#include <QTimer>
#include <QPixmap>
#include <QTouchEvent>
#include <QtConcurrent/QtConcurrent>
#include <QFuture>
#include <QtMath>
#include <QInputDialog>
#include <QMessageBox>
#include <QElapsedTimer>
#include <QtPurchasing>
#include <QTcpSocket>
#include <QDate>
#include <QMediaPlayer>
#include <QMediaPlaylist>
#include <QDir>
#include <QDesktopServices>
#include <QClipboard>